name       : libaccounts-glib
version    : '1.25'
release    : 4
source     :
    - https://gitlab.com/accounts-sso/libaccounts-glib/-/archive/1.25/libaccounts-glib-1.25.tar.gz : c0892d3923ed456d48e1cc85ac440475e1823a784ea50304309ee0a23c694c9a
license    : LGPL-2.1-only
component  : programming
summary    : GLib-based client library for the accounts database
description: |
    This project is a library for managing accounts which can be used from GLib applications. It is part of the accounts-sso project.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(glib-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sqlite3)
    - gtk-doc-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove html
    rm -rf $installdir/usr/share/gtk-doc
