name       : libaccounts-glib
version    : 1.23
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/libaccounts-glib.git : 8d14b10652b2fe6c25d8ad8334e2d5023d254313
license    : LGPL-2.1-only
component  : programming
summary    : GLib-based client library for the accounts database
description: |
    This project is a library for managing accounts which can be used from GLib applications. It is part of the accounts-sso project.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(sqlite3)
    - gtk-doc-devel
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
